name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: apt-get update && apt-get -y install make autoconf && apt-get install -y libboost-dev
    - name: build
      run: make compile
    - name: test
      run: make test
